services:
  frontend:
    build:
      context: frontend
      args:
        PORT: ${FRONTEND_PORT}
        FRONTEND_PORT: ${FRONTEND_PORT}
        BACKEND_PORT: ${BACKEND_PORT}
      #volumes:
        #  - ./app/nginx/:/etc/nginx/
        #  - ./app/dist/:/usr/share/nginx/html/
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    depends_on:
      - backend
    env_file: .env
  backend:
    image: cosmtrek/air
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}

      - FRONTEND_PORT=${FRONTEND_PORT}

      - BACKEND_PORT=${BACKEND_PORT}
    working_dir: /src
    container_name: backend
    secrets:
      - db-password
    expose:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/:/src/
    env_file: .env
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=${POSTGRES_PASSWORD_FILE}
    user: ${POSTGRES_USER}
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 5s
    secrets:
      - db-password
    expose:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgres/data
volumes:
  db-data: {}
  backend: {}
secrets:
  db-password:
    file: db/password.txt
